captcha:
  height: 80
  width: 240
  length: 6
  max_skew: 0.7
  dot_count: 80
email:
  host: smtp.qq.com
  port: 465
  from: 1504532316@qq.com
  nickname: 发件人昵称
  secret: ignwunuswjfejfdb
  is_ssl: true
es:
  url: http://127.0.0.1:9200
  username: ""
  password: ""
  is_console_print: true
gaode:
  enable: true
  key: 60697be7fb07009b5ee628b67e2391f6
jwt:
  access_token_secret: BuBpnzZOTdm080vfl0INB6q984DJ3Fr61YLMreuyY6w=
  refresh_token_secret: ZWhwTy837mpbk-7YfYH4dTCgLQMXT83mc2m26ZRGp1E=
  access_token_expiry_time: 2h
  refresh_token_expiry_time: 7d
  issuer: go_blog
mysql:
  host: 127.0.0.1
  port: 3307
  config: charset=utf8mb4&parseTime=True&loc=Local
  db_name: blog_db
  username: root
  password: root
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: info
qiniu:
  zone: z1
  bucket: whale4blog
  img_path: https://image.whale4blog.cn/
  access_key: ced7Nd85Ti8U5cEZ8MA4G9_UU0x9nYlnMGDha_uO
  secret_key: muAcxMUa9HG67N_Wnh2UxwuNv5AcMoebjekKezK5
  use_https: true
  use_cdn_domains: true
qq:
  enable: false
  app_id: "000000000"
  app_key: xxxxxxxxxxxxxxxx
  redirect_uri: http://xxx.xxx/login?flag=qq
redis:
  address: 127.0.0.1:6379
  password: ""
  db: 0
system:
  host: 0.0.0.0
  port: 8080
  env: debug
  router_prefix: api
  use_multipoint: true
  sessions_secret: mNKVl6prQdtmZvo_rfx92CtUZyAEIpLnvqmDgzaQrzQ=
  oss_type: local
upload:
  size: 20
  path: uploads
website:
  logo: "/uploads/image/2510c39011c5be704182423e3a695e91-20250815152000.jpg"
  full_logo: ""
  title: 博客标题-xxx的个人博客
  slogan: 博客标题
  slogan_en: Blog Title
  description: 博客描述
  version: 1.0.0
  created_at: "2025-1-15"
  icp_filing: icp备案号
  public_security_filing: 公安备案号
  bilibili_url: https://space.bilibili.com/xxx
  gitee_url: https://gitee.com/xxx
  github_url: https://github.com/xxx/
  name: 昵称
  job: 工作
  address: 地址
  email: xxx@qq.com
  qq_image: ""
  wechat_image: ""
zap:
  level: info
  filename: log/go_blog.log
  max_size: 200
  max_backups: 30
  max_age: 5
  is_console_print: true
ai:
  key: sk-36ecfd17617e448bbccf31206ae5ab0c
  base_url: https://api.deepseek.com
